version: 1

formatters:
  standard:
    format: '%(asctime)s  %(levelname)s  %(filename)s: %(message)s'
  error:
    format: '%(asctime)s  %(levelname)s <PID %(process)d:%(processName)s> %(lineno)d:%(name)s.%(funcName)s(): %(message)s'

filters:
  InfoFilter:
    (): utils.settings.InfoFilter
  WarnFilter:
    (): utils.settings.WarnFilter

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/log_info.log
    maxBytes: 10485760  # 10MB
    backupCount: 20
    encoding: utf8
    filters: [InfoFilter]

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: WARN
    formatter: error
    filename: logs/log_error.log
    maxBytes: 10485760  # 10MB
    backupCount: 20
    encoding: utf8
    filters: [WarnFilter]

root:
  level: NOTSET
  handlers: [console, info_file_handler, error_file_handler]
